#! /bin/sh

#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ██╗    
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗  ██║    
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔██╗ ██║    
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╗██║    
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚████║    
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝  ╚═══╝    

# polybar
pkill dunst; dunst & #notificaciones 
sudo ldm -d -u amdre #automount de dispositivos
ibus-daemon -drxR #Teclado cambiar etc
~/.config/polybar/launch.sh & 
# setxkbmap -option caps:swapescape
setxkbmap -layout us  #layout teclado 
pkill picom; picom & 
feh --bg-fill ~/Pictures/Wallpapers/wallpaperflare.com_wallpaper.jpg
#kpgrep -x sxhkd > /dev/null || sxhkd &
pkill sxhkd; sxhkd -t 1 &
xsetroot -cursor_name left_ptr & #

# monitor 
if xrandr -q | grep 'HDMI-2 connected'; then
bspc monitor eDP-1 -d 1 2 3 4 5 
bspc monitor HDMI-2 -d 6 7 8 9 0
else
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10 
fi

bspc config border_width 3 
bspc config window_gap  15
bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle  false

# Pointer
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus button1 
# bspc config swallow_first_click true 

bspc config remove_unpluggged monitors true
bspc config merge_overlapping_monitors true

# ----- COLORS -----#
bspc config active_border_color '#3c3836'
bspc config normal_border_color '#282828'
bspc config focused_border_color '#7c6f64'

# ----- RULES -----#     
bspc rule -a Screenkey manage=off
bspc rule -a Mechvibes state=floating
bspc rule -a Zathura state=tiled
# bspc rule -a Opera state=floating
