#! /bin/sh

#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ██╗    
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗  ██║    
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔██╗ ██║    
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╗██║    
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚████║    
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝  ╚═══╝    


# polybar
pkill dunst; dunst & #notificaciones 
ldm -d -u amdre #automount de dispositivos
ibus-daemon -drxR #Teclado cambiar etc
~/.config/polybar/launch.sh & 
# setxkbmap -option caps:swapescape
setxkbmap -layout us  #layout teclado 
pkill picom; picom & 
feh --bg-fill ~/Pictures/Wallpapers/download.jpeg
#kpgrep -x sxhkd > /dev/null || sxhkd &
pkill sxhkd; sxhkd &
xsetroot -cursor_name left_ptr & #

if xrandr -q | grep 'HDMI-2 connected'; then
bspc monitor eDP-1 -d I III V VII IX 
bspc monitor HDMI-2 -d II IV VI VII X
else
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

bspc config window_gap  20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled


bspc config active_border_color '#928374'
bspc config normal_border_color '#282828'
bspc config focused_border_color '#928374'

